In [1]:
%history

%history


In [ ]:
# %load greet.py
print("hii")


In [14]:
%run greet.py

hii
Wall time: 3 ms


In [16]:
sum([1,2,3])

6

In [18]:
%time sum([1,2,3])

Wall time: 0 ns


6

# python vs numpy

In [12]:
l2 = list(range(1,10))
l2

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
%time l1 = list(range(1,3000000))

Wall time: 92.1 ms


In [13]:
l3 = []
for x in l2:        #for x, y in list(enumerate(l2)):
    l3.append(x+5)  #    l2[x] += 5
print(l3)

#or
l3 = [x+5 for x in l2]
l3

[6, 7, 8, 9, 10, 11, 12, 13, 14]


[6, 7, 8, 9, 10, 11, 12, 13, 14]

In [6]:
%time [x*5 for x in l1][:11]

Wall time: 466 ms


[5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55]

In [14]:
list(enumerate(["A","B","C"]))

[(0, 'A'), (1, 'B'), (2, 'C')]

In [2]:
l2 = [1, 2, 3, 4, 5, 6, 7, 8, 9]
for i, v in list(enumerate(l2)):
    l2[i] += 5
l2

[6, 7, 8, 9, 10, 11, 12, 13, 14]

In [8]:
l2 = [
     [1,2,3],
     [4,5,6],
     [7,8,9]]
for li, l in list(enumerate(l2)):
    for i, v in list(enumerate(l)):
        l[i] += 5
l2

[[6, 7, 8], [9, 10, 11], [12, 13, 14]]

# numpy and multidimensional array

In [1]:
#import numpy as *
import numpy as np #preffered

In [2]:
l = [1,2,3]
print(sum(l)) # python sum func -->slow
print(np.sum(l)) # numpy sum func  -->fast
# to differentiate both it is better to use alias np

6
6


In [3]:
%time l2 = np.arange(1,3000000)

Wall time: 14 ms


In [4]:
l2

array([      1,       2,       3, ..., 2999997, 2999998, 2999999])

In [5]:
print(l2 *2)

[      2       4       6 ... 5999994 5999996 5999998]


array 
- same datatype
- fixed length no append function

In [16]:
l = [1, 2, 3, 4, 5]
arr = np.array(l)
print(arr)
arr is l

[1 2 3 4 5]


False

In [ ]:
def fun (l,e,r,t)

In [3]:
arr = np.array([1,2,3,4,5,6.8])
print("dimension of array is: ", arr.ndim)
print("shape is: ", arr.shape) #number of elements in each dimension (size of each dimension)
print("data type: ", arr.dtype)
arr

dimension of array is:  1
shape is:  (6,)
data type:  float64


array([1. , 2. , 3. , 4. , 5. , 6.8])

In [3]:
arr = np.array([[1,2,3], [4,5,"a"]])
print("dimension of array is: ", arr.ndim) #returns scalar
print("shape is: ", arr.shape) #returns tuple
print("data type: ", arr.dtype)
print("size: ", arr.size)
arr

dimension of array is:  2
shape is:  (2, 3)
data type:  <U11
size:  6


array([['1', '2', '3'],
       ['4', '5', 'a']], dtype='<U11')

In [2]:
arr = np.random.randn(2,3) # 4 sets having further 2 rows each having 3 coloms/elements
print("dimension of array is: ", arr.ndim)
print("shape is: ", arr.shape)
print("data type: ", arr.dtype)
arr
# ...randn(2,3) 2d array 2 row and 3 columns
# ...randn(0) 1d array with 0 elements
# ...randn(2,3,4,5) 4d array 

dimension of array is:  2
shape is:  (2, 3)
data type:  float64


array([[ 0.51065635, -0.9263888 , -1.19584676],
       [-0.47512364, -0.39065376, -1.45214705]])

In [3]:
arr = np.random.randn(4,2,3) # 4 sets having further 2 rows each having 3 coloms/elements
print("dimension of array is: ", arr.ndim)
print("shape is: ", arr.shape)
print("data type: ", arr.dtype)
arr
# ...randn(2,3) 2d array 2 row and 3 columns
# ...randn(0) 1d array with 0 elements
# ...randn(2,3,4,5) 4d array 

dimension of array is:  3
shape is:  (4, 2, 3)
data type:  float64
Object `np.randn` not found.


In [6]:
l1 = np.arange(27)
print(l1.ndim, l1.shape, l1.dtype)
l1

1 (27,) int32


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [73]:
l1 = np.arange(27).reshape((3,3,3))
print(l1.ndim, l1.shape, l1.dtype)
l1

3 (3, 3, 3) int32


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [75]:
l1+5 #only numpy supports this othervise in python use for loop

array([[[ 5,  6,  7],
        [ 8,  9, 10],
        [11, 12, 13]],

       [[14, 15, 16],
        [17, 18, 19],
        [20, 21, 22]],

       [[23, 24, 25],
        [26, 27, 28],
        [29, 30, 31]]])

In [77]:
l1 ** .5 # square root of each element in l1

array([[[0.        , 1.        , 1.41421356],
        [1.73205081, 2.        , 2.23606798],
        [2.44948974, 2.64575131, 2.82842712]],

       [[3.        , 3.16227766, 3.31662479],
        [3.46410162, 3.60555128, 3.74165739],
        [3.87298335, 4.        , 4.12310563]],

       [[4.24264069, 4.35889894, 4.47213595],
        [4.58257569, 4.69041576, 4.79583152],
        [4.89897949, 5.        , 5.09901951]]])

# creating ndarrays

np.array

In [19]:
# creates deep copy

l1 = [1,2,3]


a = np.array(l1)
b = np.array(a)

print(type(a))
a is b

<class 'numpy.ndarray'>


False

np.asarray

In [94]:
# 1 array->Shallow Copy
# 2 array->Change dtype -> Deep Copy
# 3 if not array->Deep copy

l1 = [1,2,3]

a = np.asarray(l1) #2
b = np.asarray(a)  #1
c = np.asarray(b, dtype=np.float64) #3

print(l1 is a)
print(a is b)
print(b is c)

c.dtype

False
True
False


dtype('float64')

In [30]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
a[2].shape

(3,)

In [32]:
a[2,:]

array([6, 7, 8])

In [33]:
a[2:,:]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [9]:
np.arange(15).reshape(1,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [8]:
np.arange(15).reshape(3,-1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [58]:
arr = np.arange(1*3*2*4).reshape((2, 4, 1,3))
arr

array([[[[ 0,  1,  2]],

        [[ 3,  4,  5]],

        [[ 6,  7,  8]],

        [[ 9, 10, 11]]],


       [[[12, 13, 14]],

        [[15, 16, 17]],

        [[18, 19, 20]],

        [[21, 22, 23]]]])

In [78]:
arr.transpose() #(3, 1, 4, 2)

array([[[[ 0, 12],
         [ 3, 15],
         [ 6, 18],
         [ 9, 21]]],


       [[[ 1, 13],
         [ 4, 16],
         [ 7, 19],
         [10, 22]]],


       [[[ 2, 14],
         [ 5, 17],
         [ 8, 20],
         [11, 23]]]])

In [76]:
arr.transpose((2, 3, 0, 1)) #(1,3,2,4)

array([[[[ 0,  3,  6,  9],
         [12, 15, 18, 21]],

        [[ 1,  4,  7, 10],
         [13, 16, 19, 22]],

        [[ 2,  5,  8, 11],
         [14, 17, 20, 23]]]])

In [80]:
arr.swapaxes(2,0) #(1,4,2,3)


array([[[[ 0,  1,  2],
         [12, 13, 14]],

        [[ 3,  4,  5],
         [15, 16, 17]],

        [[ 6,  7,  8],
         [18, 19, 20]],

        [[ 9, 10, 11],
         [21, 22, 23]]]])

In [27]:
dic = {1:2,2:3,3:4}
a = np.array(dic)
np.dtype(a)

TypeError: data type not understood

In [71]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
np.hsplit(a,3)

[array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]]), array([[3],
        [6],
        [9]])]

In [74]:
np.split(a,3,axis=1)

[array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]]), array([[3],
        [6],
        [9]])]